### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by lgritz** [MishaalRahmanGH/Ultra_HDR_Samples#2]
Hi, just to fully clarify the issues for those of us with picky legal departments, would you mind adding an official LICENSE file that describes how these can be used by other projects? Probably one of the creative commons licenses will do (I personally recommend [Creative Commons Attribution 4.0 Unported License](http://creativecommons.org/licenses/by/4.0/)), because copyright law in most places is actually that "no posted license" by default means "it's not ok to use it at all for any purpose".

Thanks!

**Comment by MishaalRahmanGH** [comment]
Done! Feel free to use the material as you see fit!

**Comment by lgritz** [comment]
Thanks so much! These examples are very helpful.
